name: Run linters
on: 
  push:
  pull_request:

env:
  CARGO_NIGHTLY_TOOLCHAIN: nightly-2023-09-05

jobs:
  check:
    strategy:
      matrix:
        target: [x86_64-pc-windows-gnu, x86_64-unknown-linux-gnu]
        features: ["std", "nosym", "alloc", "unsafe_conversions"]

    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}
          target: ${{ matrix.target }}
          components: clippy,rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}
          args: --features=${{ matrix.features }} --target=${{ matrix.target }}