name: Run linters
on: push

jobs:
  check:
    strategy:
      matrix:
        features: ["std", "nosym"]

    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: x86_64-pc-windows-gnu
          profile: minimal
          toolchain: nightly
          override: true

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features=${{ matrix.features }} -Zbuild-std=core,alloc,panic_unwind,panic_abort,std