name: Run linters
on: push

jobs:
  check:
    strategy:
      matrix:
        features: ["std", "nosym"]

    name: Run clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: nightly
          target: x86_64-pc-windows-gnu
          components: clippy, rust-src

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --features="${{ matrix.features }}" -Zbuild-std="core,alloc,panic_unwind,panic_abort,std"