name: Run tests
on: 
  push:
    branches:
      main
  pull_request:
    branches: 
      - main

env:
  CARGO_NIGHTLY_TOOLCHAIN: nightly-2023-09-05

jobs:
  test-windows:
    strategy:
      matrix:
        features: ["std", "nosym", "alloc"]
        target: [x86_64-pc-windows-gnu]

    name: Run tests
    runs-on: self-hosted
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}
          target: ${{ matrix.target }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}
          args: --target=${{ matrix.target }} --features=${{ matrix.features }}
  test-linux:
    strategy:
      matrix:
        features: ["std", "nosym", "alloc"]
        target: [x86_64-unknown-linux-gnu]

    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          override: true
          profile: minimal
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}
          target: ${{ matrix.target }}

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          toolchain: ${{ env.CARGO_NIGHTLY_TOOLCHAIN }}
          args: --target=${{ matrix.target }} --features=${{ matrix.features }}